name             'jenkins'
maintainer       'chakravarthy soma'
maintainer_email 'chakravarthy.soma@bestbuy.com'
license          'All rights reserved'
description      'Installs/Configures jenkins'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 	 'apt'
depends    'nodejs'
depends    'ark', '~> 1.0.1'
depends    'nginx'
depends    '7-zip'
depends    'ark'
depends    'bluepill'
depends    'chef_handler'
depends    'compat_resource'
depends    'nginx-repo'
depends    'iptables'
depends    'nodejs'
depends    'ohai'
depends    'packagecloud'
depends    'R'
depends    'rsyslog'
depends    'runit'
depends    'seven_zip'
depends    'tools'
depends    'windows'
depends    'yum'
depends    'yum-epel'
